# Generated by Django 2.1.7 on 2019-07-05 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('os_client', '0001_initial'),
        ('os_admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blockproperty',
            fields=[
                ('no', models.AutoField(primary_key=True, serialize=False)),
                ('block_date', models.DateField(auto_now_add=True)),
                ('client_un', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='os_client.Client')),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('no', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('photo', models.ImageField(upload_to='property/')),
                ('size', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=50)),
                ('facing', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('comment', models.CharField(max_length=50)),
                ('add_date', models.DateField(auto_now_add=True)),
                ('sold_date', models.DateField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='os_admin.Agent')),
            ],
        ),
        migrations.CreateModel(
            name='Soldproperty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_sold', models.DateField(auto_now_add=True)),
                ('client_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='os_client.Client')),
                ('property_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='os_agent.Property')),
            ],
        ),
        migrations.AddField(
            model_name='blockproperty',
            name='property_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='os_agent.Property'),
        ),
    ]
