# Generated by Django 2.1.7 on 2019-07-05 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('name', models.CharField(max_length=30)),
                ('contact_no', models.IntegerField()),
                ('photo', models.ImageField(upload_to='client/')),
                ('address', models.TextField()),
                ('client_un', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('client_pwd', models.CharField(max_length=30)),
                ('otp', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('no', models.AutoField(primary_key=True, serialize=False)),
                ('comment', models.TextField()),
                ('client_un', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='os_client.Client')),
            ],
        ),
    ]
