# Generated by Django 2.1.7 on 2019-07-05 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adminlogin',
            fields=[
                ('contactno', models.IntegerField(primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=20)),
                ('otp', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('no', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('photo', models.ImageField(upload_to='agent/')),
                ('address', models.TextField()),
                ('agent_un', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('agent_pwd', models.CharField(max_length=30)),
                ('contactno', models.IntegerField()),
                ('otp', models.IntegerField()),
            ],
        ),
    ]
